[package]
name = "nu-jupyter-kernel"
version = "0.1.0"
edition = "2021"

[package.metadata.jupyter]
protocol_version = "5.4"

[dependencies]
nu-cmd-extra = { version = "0.92.2", path = "../nushell/crates/nu-cmd-extra" }
nu-cmd-lang = { version = "0.92.2", path = "../nushell/crates/nu-cmd-lang" }
nu-command = { version = "0.92.2", path = "../nushell/crates/nu-command" }
nu-engine = { version = "0.92.2", path = "../nushell/crates/nu-engine" }
nu-parser = { version = "0.92.2", path = "../nushell/crates/nu-parser" }
nu-protocol = { version = "0.92.2", path = "../nushell/crates/nu-protocol" }

clap = { version = "4.5.4", features = ["derive"] }
thiserror = "1.0.58"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
bytes = "1.6.0"
uuid = "1.8.0"
chrono = "0.4.38"
dirs = "5.0.1"
static-toml = "1.2.0"
const_format = "0.2.32"
hmac = "0.12.1"
sha2 = "0.10.8"
hex = "0.4.3"
mime = "0.3.17"
mime_guess = "2.0.4"
zmq = "0.10.0"
derive_more = "0.99.17"
miette = { version = "7.2.0", features = ["fancy"] }
atomic_enum = "0.3.0"
parking_lot = "0.12.2"
