[package]
name = "nu_plugin_plotters"
version = "0.1.0-wip"
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
# nu
nu-plugin = { version = "0.97" }
nu-protocol = { version = "0.97" }
nu-engine = { version = "0.97" }

# plotting
plotters = "0.3.6"

# serialization, needed for custom values
serde = { version = "1", features = ["derive"] }
typetag = "0.2"

# drawing to the terminal
icy_sixel = "0.1"

# misc
indoc = "2"
