name: continous-integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crates:
          - nu_plugin_plotters
          - nu-jupyter-kernel
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo check -p ${{ matrix.crates }} 

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo doc --workspace 
