name: continous-integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      
      - name: Check nu_plugin_plotters
        run: cargo check -p nu_plugin_plotters 

      - name: Check nu-jupyter-kernel
        run: cargo check -p nu-jupyter-kernel

      - name: Doc
        run: cargo doc
