name: continous-integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crates:
          - nu_plugin_plotters
          - nu-jupyter-kernel
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} (check ${{ matrix.crates }})
      - run: cargo check -p ${{ matrix.crates }} 

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} (doc)
      - run: cargo doc --workspace 

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crates:
          - nu_plugin_plotters
          - nu-jupyter-kernel
    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} (test ${{ matrix.crates }})
      - run: cargo test -p ${{ matrix.crates }} 

  integration-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} (run nu-jupyter-kernel)
      - run: cargo run register --user
      - name: Read .python-version
        id: python-version
        run: echo "python-version=$(cat .python-version)" >> $GITHUB_OUTPUT
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python-version.outputs.python-version }}
      - uses: yezz123/setup-uv@v4
      - run: uv sync
      - uses: actions/cache@v4
        with:
          path: .venv/
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
      - run: uv run pytest
